name: brain_dev_notification
description: "A local notification Flutter project."
version: 1.0.5
homepage: https://github.com/Grafritz/brain_dev_notification_plugin.git

#  dart pub publish --dry-run   #// Vérifier avant chaque nouvelle version
#  dart pub login
#  dart pub publish            # Publier la mise à jour

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1
  plugin_platform_interface: ^2.1.8


  http: ^1.3.0 # A cause Plugin
  http_parser: ^4.1.2 # A cause Plugin
  intl: ^0.19.0 # A cause Plugin
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.1.0

  get: ^4.7.2 # A cause Plugin
  path_provider: ^2.1.5 # A cause Plugin
  timeago: ^3.7.0 # A cause Plugin
  timezone: ^0.10.0 # A cause Plugin

  # rm -rf ~/.pub-cache/git
  brain_dev_tools: ^1.0.5
  brain_dev_business: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: net.braindev.brain_dev_notification
        pluginClass: BrainDevNotificationPlugin
      ios:
        pluginClass: BrainDevNotificationPlugin
      web:
        pluginClass: BrainDevNotificationWeb
        fileName: brain_dev_notification_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
